use_frameworks!

target 'BBAEPatch_Example' do
  pod 'BBAEPatch', :path => '../'

  target 'BBAEPatch_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
